name: Generate Daily Post1

on:
  schedule:
    # 每天UTC时间00:00运行（北京时间08:00）
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Generate new post
      run: python script/generate.py
      
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add content/
        git commit -m "Auto-generate post for $(date +'%Y-%m-%d')" || echo "No changes to commit"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
