name: Generate Daily Post

on:
  push:
    branches: [ main, master ]
  schedule:
    # 每天UTC时间0点运行（北京时间8点）
    - cron: '0 0 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  generate-post:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install pytz
        
    - name: 运行生成脚本
      run: |
        python generate_post.py
        
    - name: 提交生成的文件
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add post/
        git commit -m "自动生成北京时间帖子 [$(date +'%Y-%m-%d %H:%M:%S')]" || echo "没有变更可提交"
        git push
